### ISSUE TITLE
HERE: API updates - appId and appCode not supported anymore

### ISSUE THREAD

**Issue by pa-lem** [nchaulet/node-geocoder#297] opened 2020-03-24 11:12 UTC
Due to recent updates, **appId** and **appCode** are not supported anymore (**for new Here projects**, old projects still work for now, but will be depreciated).

We need to make a standard fetch with url and token for example:

`https://geocode.search.hereapi.com/v1/geocode?q=<YOUR_SEARCH>&apiKey=<YOUR_API_KEY>`

**Comment by nchaulet** [comment] 2020-03-24 18:35
Thanks to report the issue going to fix this soon

**Comment by jvolker** [comment] 2020-03-27 23:02
Duplicate of #286

**Comment by nchaulet** [comment] 2020-04-07 20:58
Resolved by #302

**Closed** 2020-04-10 21:43 UTC
Labels: enhancement
