### ISSUE TITLE
OpenStreetMap // Node Error Body used already

### ISSUE THREAD

**Issue by LBeckX** [nchaulet/node-geocoder#357] opened 2024-06-18 12:22 UTC
Hi, I am currently getting the following error with OpenStreetMap.

```log
HttpError: body used already for: https://nominatim.openstreetmap.org/search?accept-language=de-DE&addressdetails=1&q=Erlanger Straße+91080+Deutschland&format=json
```

This is my implementation that worked before.

```typescript

async function getGeoLocationAddresses(address: string) {
        const geocoder = NodeGeoCoder({provider: 'openstreetmap', email: 'test@test.de', language: 'de-DE'})
        const response = await geocoder.geocode(address + ' Deutschland')
        if (!response[0]) {
            throw new Error(`Can not get geolocation - response is empty by address: ${address}`)
        }
        return response
}

```

**Comment by SultanGabriel** [comment] 2024-06-18 12:55
same here

**Comment by loique** [comment] 2024-06-18 15:02
same here

**Comment by victordalet** [comment] 2024-06-21 08:28
Same here, but we can still request the API

```js
const response = await fetch(`https://nominatim.openstreetmap.org/search?addressdetails=1&q=${location.address.replace(" ", "+")}&format=json`)
const data = await response.json();
 ```

**Comment by farrukh-educative** [comment] 2024-07-02 09:55
The same issue is being faced here. Do we have any update if the issue is fixed or when can it be fixed? Thanks.

**Comment by SultanGabriel** [comment] 2024-07-02 10:04
> The same issue is being faced here. Do we have any update if the issue is fixed or when can it be fixed? Thanks.

A fix already should exist for the bug PR #346. I haven't looked again if the PR got merged but you could copy the commit for a temporary fix, it's 4 or 5 lines that need changing

**Comment by isntfunny** [comment] 2024-07-05 22:11
Could you release the new version? The PR got merged 2 weeks ago already

**Comment by nchaulet** [comment] 2024-11-30 15:28
This has been released

**Closed by nchaulet** 2024-11-30 15:28 UTC
